# Use the official Node.js image as a parent image
FROM --platform=linux/amd64 node:16

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json (if available) to the container
COPY package*.json ./

# Install the dependencies inside the container
RUN npm install

# Copy the rest of your app's source code from your local environment to the container
COPY . .

# Build the app for production
RUN npm run build
#???
# Command to run the app using Vite's production server
CMD ["npm", "run", "serve"]