apiVersion: v1
kind: Service
metadata:
  name: spotify-clone2-service
spec:
  selector:
    app: spotify-clone2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
